### ISSUE TITLE
Relation to forbidExtraProps from airbnb/prop-types?

### ISSUE THREAD

**Issue by vvo** [airbnb/prop-types-exact#10]
Hi there, it seems this package and forbidExtraProps from airbnb/prop-types are similar. Can you explain the differences and when should we use this or forbidExtraProps?

Thanks!

**Comment by ljharb** [comment]
Yes, they're quite similar :-p https://github.com/airbnb/prop-types/blob/master/src/forbidExtraProps.js#L1-L3

airbnb-prop-types just re-exports prop-types-exact; use whichever one you like.

**Comment by rohit-rautt** [comment]
Hi @vvo  did this work for you ?
