### ISSUE TITLE
Please, do you have a lint rule for that? 

### ISSUE THREAD

**Issue by brunoreis** [airbnb/prop-types-exact#11]
I'm seeing these now that I use `exact`: 

![Screen Shot 2020-06-02 at 11 22 23](https://user-images.githubusercontent.com/217240/83531427-5a5f6280-a4c3-11ea-86be-105bdf9dd456.png)

![Screen Shot 2020-06-02 at 11 21 14](https://user-images.githubusercontent.com/217240/83531341-3d2a9400-a4c3-11ea-8451-2d4cc3dbe6cf.png)

**Comment by ljharb** [comment]
You need to define propWrapperFunctions in eslint-plugin-react’s settings. https://github.com/yannickcr/eslint-plugin-react#configuration

**Comment by brunoreis** [comment]
Thanks
