### ISSUE TITLE
doesn't work in my browser when specialProperty is Symbol

### ISSUE THREAD

**Issue by plantvsbirds** [airbnb/prop-types-exact#3]
I have react@15 and chrome 59.0.3071.115.
With a little tweak in code, I was able to find out the possible cause.

Firstly I made `specialProperty` any string, including `zeroWidthSpace`, works fine.
Then I changed it back to Symbol, the function was not called. 

then I attached a debugger to validator..
```
  propertyOne: PropTypes.string,
  propertyTwo: () => {
    debugger
    return null
  },
```
I was able to reach this frame
![image](https://user-images.githubusercontent.com/6203430/27894640-fe69d2da-623f-11e7-9215-21e67d90e0d6.png)

and the checkType function
![image](https://user-images.githubusercontent.com/6203430/27894645-0875f74a-6240-11e7-9631-3826611f0c53.png)

It turns out that when doing the `for... in`, the symbol would not be found as a key.
![image](https://user-images.githubusercontent.com/6203430/27894663-21353a3e-6240-11e7-941d-8afa95de2c0a.png)
![image](https://user-images.githubusercontent.com/6203430/27894710-77b938ec-6240-11e7-80d9-0a6513f5506a.png)

**Comment by plantvsbirds** [comment]
I have no idea why tests would pass. My speculation would be... 

1. the test environment doesn't support Symbol. 
2. the test was run on native HTML element, instead of a React component, and React treated these two with different prop validation logic

**Comment by ljharb** [comment]
I'm a bit confused - native HTML elements can't have propTypes, only custom components can.

However, if they're indeed using `for..in`, then it definitely won't work with symbols. In that case, I'm not sure why [this test](https://github.com/airbnb/prop-types-exact/blob/master/test/index.jsx#L84-L86) is passing in Symbol-supporting node versions. I'll add some tests and see if I can reproduce this problem.

**Comment by ljharb** [comment]
Thanks, v1.1.1 incoming.
