### ISSUE TITLE
Uniformize wording on readme 

### ISSUE THREAD

**Issue by jjant** [airbnb/prop-types-exact#4]
The description says that the library will throw an error on non explicitly set props, but in the example, it says it will throw a "warning".

Ambiguity should be removed by using only "error".

**Comment by ljharb** [comment]
It says "Will error" consistently - it doesn't specify "throw". Where are you finding "throw"?

**Comment by jjant** [comment]
I meant here:

```jsx
import PropTypes from 'prop-types';
import exact from 'prop-types-exact';

function Foo({ foo, bar }) {
  return <div>{foo}{bar}</div>
}
Foo.propTypes = exact({
  foo: PropTypes.string,
  bar: PropTypes.number,
});

<Foo foo="hi" bar={3} /> // no warnings

<Foo foo="hi" bar={3} baz="extra" /> // propTypes warning!
```

It should be `no errors`, not `no warnings` and similarly below.

**Comment by ljharb** [comment]
Ah, gotcha.

So, I guess it *could* say that - I'm really not sure I see why it *should*?
