### ISSUE TITLE
Not working with ESLint plugin `eslint-plugin-react`

### ISSUE THREAD

**Issue by almarto** [airbnb/prop-types-exact#8]
Is there any way to make it work together with the ESLint plugin `eslint-plugin-react` or is there any ESLint plugin which I'm missing?

The rules which I'm currently using and aren't compatible with the usage of prop-types-exact are `no-unused-prop-types` and `prop-types`

**Comment by ljharb** [comment]
https://github.com/airbnb/react-dates/blob/master/.eslintrc#L32-L34
