### ISSUE TITLE
Allow some props (without using them)

### ISSUE THREAD

**Issue by jdeniau** [airbnb/prop-types-exact#9]
Some HOC does provide multiple props, when sometimes you do not want all of them.

Example: [withRouter from react-router](https://reacttraining.com/react-router/web/api/withRouter) adds `match`, `location` and `history`.

A simple approach might to add them in the prop-types, but [no-unused-prop-types](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/no-unused-prop-types.md) will throw in this case.

Imagine the following component:
```jsx
function SomeComponent({ history }) {
  return <button onClick={() => history.push('/')}>go somewhere</button>;
}
SomeComponent.propTypes = exact({
  history: PropTypes.object.isRequired,
});

export default withRouter(SomeComponent);
```

Actually I would have to do this:
```jsx
function SomeComponent({ history }) {
  return <button onClick={() => history.push('/')}>go somewhere</button>;
}
SomeComponent.propTypes = exact({
  history: PropTypes.object.isRequired,
  match: PropTypes.any, // eslint-disable-line
  location: PropTypes.any, // eslint-disable-line
});

export default withRouter(SomeComponent);
```

Should the `exact()` function takes a `ignore` list parameter like this ?
```jsx
function SomeComponent({ history }) {
  return <button onClick={() => history.push('/')}>go somewhere</button>;
}
SomeComponent.propTypes = exact({
  history: PropTypes.object.isRequired,
}, ['match', 'location']);

export default withRouter(SomeComponent);
```

**Comment by ljharb** [comment]
I think using PropTypes.any is the correct solution, if you can’t borrow the PropTypes from the wrapped component (which would be the best solution).

Complicating this api solely to avoid you having to use eslint-disable comments doesn’t seem like a worthy tradeoff to me.

**Comment by jdeniau** [comment]
Simple API is nice :+1:
